name: ibzer_bizart
description: A children school App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.5.0
  provider: ^6.0.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^8.3.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  #firebase_messaging: ^10.0.0
  firebase_storage: ^10.0.2
  fluttertoast: ^8.0.8
  http: ^0.13.3
  #file_picker: ^3.0.0
  #dio: ^4.0.0
  #share_extend: ^1.1.9
  permission_handler: ^8.1.4+2
  #badges: ^1.2.0
  #image_picker: ^0.7.3
  #photo_view: ^0.11.1
  #image_cropper: ^1.4.0
  google_sign_in: ^5.0.7
  url_launcher:
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  progress_dialog: ^1.2.4
  font_awesome_flutter: ^9.1.0
  #sticky_grouped_list: ^1.3.0
  #flutter_local_notifications: ^5.0.0
  flutter_autolink_text: ^1.0.0+1
  flutter_svg: ^0.22.0
  flutter_staggered_grid_view: ^0.4.0
  #paginate_firestore: ^1.0.2
  cupertino_icons: ^1.0.3
  flutter_paystack: ^1.0.5+1
  advance_pdf_viewer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - images/
    - assets/